petstore:
  service:
    pet:
     url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
  security:
    # Enable this together with 'cloud.azure.active-directory.b2c.enabled = true' in Module 10
    enabled: false
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      active-directory:
        b2c:
          # Enable this together with 'petstore.service.security.enabled = true' in Module 10
          enabled: false