petstore:
  service:
    pet:
     url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
  security:
    # Enable this together with 'cloud.azure.active-directory.b2c.enabled = true' in Module 10
    enabled: true
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      active-directory:
        b2c:
          # Enable this together with 'petstore.service.security.enabled = true' in Module 10
          enabled: true
          base-uri: ${PETSTOREAPP_B2C_BASE_URI}
          credential:
            client-id: ${PETSTOREAPP_B2C_CLIENT_ID}
            client-secret: ${PETSTOREAPP_B2C_CLIENT_SECRET}
          login-flow: sign-up-or-sign-in
          logout-success-url: ${PETSTOREAPP_B2C_LOGOUT_URL}
          user-flows:
            sign-up-or-sign-in: B2C_1_signupsignin
            profile-edit: B2C_1_profileediting
            password-reset: B2C_1_passwordreset