services:
  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://petstorepetservice:8081
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - PETSTOREORDERSERVICE_URL=http://petstoreorderservice:8083
      # Set to true if you have a connection string set in .env:
      - APPLICATIONINSIGHTS_ENABLED=true
      # Enables B2C login/logout flow locally. Set additional configs in .env:
      - PETSTOREAPP_B2C_ENABLED=true
      # Enables Spring Security locally. Use together with B2C settings above:
      - PETSTORE_SECURITY_ENABLED=true

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082